Andrey Tkachuk: 10 solutions for Bioinformatics Stronghold
Bioinformatics-internship-EPAM/rosalind-solutions-2022 pull request #13
Opened 2022-03-27 21:43 UTC by Tka4uk-Andrei

2022-03-30 17:26 UTC, darina-ovis requested changes
Я вижу только 7 задач. Уберите пожалуйста .gitignore и добавьте входные файлы, которые читаются в классах.

2022-03-31 22:58 UTC, Tka4uk-Andrei commented
> Я вижу только 7 задач. Уберите пожалуйста .gitignore и добавьте входные файлы, которые читаются в классах.

добавил оставшиеся 3 задачи и входные файлы

2022-03-31 23:01 UTC, Tka4uk-Andrei commented on Dna.java
> +    static private String INPUT_FILE_NAME = "rosalind_dna.txt";
Add task descriptions for each file with links to Rosalind site. Also add `readme.md` file

2022-04-06 09:43 UTC, darina-ovis approved these changes

2022-04-06 09:44 UTC, merged