Васильев Максим: 5 задач из Bioinformatics Armory
Bioinformatics-internship-EPAM/rosalind-solutions-2022 pull request #3
Opened 2022-03-17 12:21 UTC by Venjilin

2022-03-17 16:02 UTC, darina-ovis requested changes
Имена файлов должны совпадать с именами классов, иначе код не компилируется. Также если в классе указано название пакета, то классы должны лежат в этом пакете. Не хватает файлов input-ов для успешной работы Ваших классов. Пожалуйста, добавьте правильную структуру. Я оставила несколько комментариев.

2022-03-18 10:17 UTC, Venjilin commented on Vasiliev_Maksim/ReadQualityDistribution.java
> +            tmp = reader.readLine();
Я в  новом коммите воспользовался предложенной конструкцией.

2022-03-18 10:19 UTC, Venjilin commented on Vasiliev_Maksim/ReadQualityDistribution.java
> +            sum += str.charAt(i) - 33;
Там же в файле качество символа обозначается символами. Минимальное качество соответствует символу с кодом 33. В новом коммите я вынес это как константу и место числа поставил символ.

2022-03-18 10:19 UTC, Venjilin commented on Vasiliev_Maksim/GenBankIntroduction.java
> +        String base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi";
Я вынес

2022-03-18 10:22 UTC, Venjilin commented on Vasiliev_Maksim/FASTQformatintroduction.java
> +    public static void main(String[] args)
Используя предложенную ранее конструкцию, я сократил метод. Вообще там большая часть метода это была много раз повторяющаяся конструкция try catch. Я объединил их в одну и функция сильно ужалась.

2022-03-29 16:12 UTC, darina-ovis approved these changes
Со структурой пакетов и тестовыми файлами все равно проблема, но несмотря на это Вы проделали отличную работу.

2022-03-29 16:12 UTC, merged